id: P010674
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18925
  title: རྒྱུ་དངོས་བདག་དབང་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    0dc102ad1bda479b94d4d2d70b84fecd:
      image_group_id: I8LS18927
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
